# Generated by Django 4.2.1 on 2023-05-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='topic',
            name='blog_header_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='posts/'),
        ),
    ]
