# Generated by Django 4.2.1 on 2023-05-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_alter_topic_options_topic_blog_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='blog_header_image',
            field=models.ImageField(blank=True, default='image/default.jpg', upload_to='image/'),
        ),
    ]
